version: '3.3'

services:
  db:
    image: mysql:latest
    networks:
      - fullstack
    restart: always
    environment:
      - MYSQL_DATABASE=muzz
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=supersecure
      - MYSQL_ROOT_PASSWORD=supersecure
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
  api:
    image: muzz-api:local
    networks:
      - fullstack
    restart: always
    environment:
      - API_PORT=:5001
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=admin
      - DB_PASSWORD=supersecure
      - DB_NAME=muzz
      - AUTH_SECRET_KEY=supersecret
    ports:
      - '5001:5001'
    expose:
      - '5001'

networks:
 fullstack:
    driver: bridge

volumes:
  db: