version: '3.3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=muzz
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=supersecure
      - MYSQL_ROOT_PASSWORD=supersecure
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql

volumes:
  db: